title: Sai Swaroop Gali
logo: /assets/Profile.png
description: Data Alchemist | Bridging the Gap Between Data and Value | AWS Certified Cloud Engineer

Passionate data enthusiast skilled in transforming data into actionable insights and driving organizational success. ðŸš€ðŸ“Š
#show_downloads: true
#email: Sai-Swaroop.Gali@outlook.com
#location: Emden, Germany
theme: jekyll-theme-minimal
